name: TreantJS Issue
description: 'ONLY FOR DEVELOPERS: Issue from treantjs. Use this templates: Question, Bug, Feature.'
title: '[Treantjs]: '
labels: ['treantjs', 'good first issue', 'help wanted']
projects: ['egor-progger/3']
body:
  - type: textarea
    id: description
    attributes:
      label: Description from treantjs issue
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Treantjs issue link
    validations:
      required: true
